# Generated by Django 5.0.5 on 2024-05-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='healthcareprof',
            old_name='healthCareProf_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='medicalcase',
            old_name='medical_case_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='medical_record_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='id',
        ),
    ]
