# Generated by Django 5.0.5 on 2024-05-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='healthcareprof',
            table='healthcare_professional',
        ),
        migrations.AlterModelTable(
            name='hospital',
            table='hospital',
        ),
        migrations.AlterModelTable(
            name='medicalcase',
            table='medical_case',
        ),
        migrations.AlterModelTable(
            name='medicalrecord',
            table='medical_record',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient',
        ),
    ]
